apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels: { app: {{ .Release.Name | quote }} }
  template:
    metadata:
      labels: { app: {{ .Release.Name | quote }} }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: w
          image: traefik/whoami:v1.10.2
          env: [{ name: WHOAMI_PORT_NUMBER, value: "8080" }]
          ports: [{ containerPort: 8080 }]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
