---
- name: Add Helm (Buildkite) repository
  ansible.builtin.deb822_repository:
    name: helm-debian
    types: deb
    uris: https://packages.buildkite.com/helm-linux/helm-debian/any/
    suites: any
    components: main
    architectures: amd64
    signed_by: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey

- name: Update apt cache after Helm repository
  ansible.builtin.apt:
    update_cache: true

- name: Install Talos tools packages
  apt:
    name: "{{ talos_tools_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
