# Generated by Terraform into k8s_config_dir (default /opt/home.tf/k8s). TSIG material lives in Secret external-dns-rfc2136.
provider:
  name: rfc2136

extraArgs:
  - --rfc2136-host=${rfc2136_host}
  - --rfc2136-port=${rfc2136_port}
  - --rfc2136-zone=${dns_zone_label}
  - --rfc2136-tsig-secret-alg=${tsig_algorithm}

env:
  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    valueFrom:
      secretKeyRef:
        name: external-dns-rfc2136
        key: rfc2136-tsig-secret
  - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
    valueFrom:
      secretKeyRef:
        name: external-dns-rfc2136
        key: rfc2136-tsig-keyname

txtOwnerId: ${txt_owner_id}

domainFilters:
  - ${dns_zone_label}

sources:
%{ for s in sources ~}
  - ${s}
%{ endfor ~}

policy: ${policy}

logLevel: info
interval: 1m

rbac:
  create: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
